// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AmsTray } from "./AmsTray";
import type { AmsUnit } from "./AmsUnit";

/**
 * The full AMS picture: every unit and tray, the external spool, and the
 * active/target/previous tray pointers (the live colour-swap signal — the tray
 * *array* only arrives in full pushalls, the pointers in deltas).
 */
export type Ams = { 
/**
 * Attached AMS units (`ams.ams[]`).
 */
units?: Array<AmsUnit>, 
/**
 * The external/virtual spool (`vt_tray`), surfaced even when not loaded.
 */
external: AmsTray | null, 
/**
 * Active tray id (`ams.tray_now`): `255` none, `254` external, else a tray id.
 */
active_tray: string | null, 
/**
 * Target tray during a swap (`ams.tray_tar`); `!= active_tray` ⇒ swapping.
 */
target_tray: string | null, 
/**
 * Previous tray (`ams.tray_pre`); reconstructs swap timelines.
 */
previous_tray: string | null, 
/**
 * Hex bitfield of attached units (`ams.ams_exist_bits`).
 */
ams_exist_bits: string | null, 
/**
 * Hex bitfield of occupied slots (`ams.tray_exist_bits`).
 */
tray_exist_bits: string | null, 
/**
 * Hex bitfield of genuine-Bambu (RFID) trays (`ams.tray_is_bbl_bits`).
 */
tray_is_bbl_bits: string | null, };
