// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One AMS tray/slot (`ams.ams[].tray[]` or `vt_tray`).
 */
export type AmsTray = { 
/**
 * Tray id (`id`); what `tray_now`/`tray_pre`/`tray_tar` point at.
 */
id: string, 
/**
 * Material (`tray_type`, e.g. `PLA`).
 */
material: string | null, 
/**
 * Display name (`tray_sub_brands`, e.g. `PLA Matte`).
 */
name: string | null, 
/**
 * Primary colour as RGBA hex (`tray_color`).
 */
color: string | null, 
/**
 * All colour segments (`cols`); single-colour spools mirror `color`.
 */
cols?: Array<string>, 
/**
 * Remaining filament percent (`remain`); `0`/`-1` mean unknown on the A1.
 */
remain: number | null, 
/**
 * Per-tray RFID/load status code (`state`); raw (no verified label table).
 */
state: number | null, 
/**
 * Bambu filament-preset id (`tray_info_idx`, e.g. `GFA01`).
 */
info_idx: string | null, 
/**
 * Short SKU/colour code (`tray_id_name`, e.g. `A01-R1`).
 */
id_name: string | null, 
/**
 * Stable physical-spool id (`tray_uuid`); all-zero ⇒ `None`.
 */
uuid: string | null, 
/**
 * Recommended min nozzle temp (`nozzle_temp_min`).
 */
nozzle_temp_min: number | null, 
/**
 * Recommended max nozzle temp (`nozzle_temp_max`).
 */
nozzle_temp_max: number | null, 
/**
 * `true` when this tray is the active one (`id == tray_now`).
 */
is_active: boolean, 
/**
 * `true` when this tray is the swap target (`id == tray_tar`).
 */
is_target: boolean, };
