// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AmsTray } from "./AmsTray";

/**
 * One AMS unit (`ams.ams[]`).
 */
export type AmsUnit = { 
/**
 * Physical unit id (`id`).
 */
id: string, 
/**
 * Coarse dryness bucket 1–5 (`humidity`).
 */
humidity: number | null, 
/**
 * Finer raw humidity reading (`humidity_raw`).
 */
humidity_raw: number | null, 
/**
 * Internal temperature °C (`temp`, drying-capable units).
 */
temp: number | null, 
/**
 * Remaining/active drying time (`dry_time`).
 */
dry_time: number | null, 
/**
 * The unit's trays/slots (`tray[]`).
 */
trays?: Array<AmsTray>, };
