// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A device-level fault decoded from `print_error` (0 = no error). This is a
 * **separate channel from HMS** — on the A1 mini a failing SD card reported
 * `print_error = 0x0500C010` while `hms` stayed empty, so a status view must
 * surface `print_error` in its own right.
 *
 * We don't bundle the full third-party code→text table (sources conflict; same
 * rationale as [`crate::core::hms`]) — but we DO attach a plain-language
 * [`message`](DeviceError::message) for the handful of codes verified on the
 * real device, and always emit the hex + a lookup link.
 */
export type DeviceError = { 
/**
 * Raw `print_error` value.
 */
code: number, 
/**
 * Conventional hex rendering, e.g. `0x0500C010`.
 */
hex: string, 
/**
 * Plain-language cause — present ONLY for codes we've **verified on the real
 * device** (the printer's own on-screen message). Unverified codes leave
 * this `None` and rely on `lookup_url`, so we never surface a guessed cause.
 */
message: string | null, 
/**
 * Link to Bambu's official error-code resolver for this code (we don't
 * bundle the full code→text table — sources conflict — so we point at the
 * authority instead, the same way [`crate::core::hms`] links to the wiki).
 */
lookup_url: string, };
