// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A device-level fault decoded from `print_error` (0 = no error). This is a
 * **separate channel from HMS** — on the A1 mini a failing SD card reported
 * `print_error = 0x0500C010` while `hms` stayed empty, so a status view must
 * surface `print_error` in its own right.
 *
 * We deliberately don't bundle a code→text table (sources conflict; same
 * rationale as [`crate::core::hms`]); the hex code is emitted for lookup.
 */
export type DeviceError = { 
/**
 * Raw `print_error` value.
 */
code: number, 
/**
 * Conventional hex rendering, e.g. `0x0500C010`.
 */
hex: string, 
/**
 * Link to Bambu's official error-code resolver for this code (we don't
 * bundle a code→text table — sources conflict — so we point at the
 * authority instead, the same way [`crate::core::hms`] links to the wiki).
 */
lookup_url: string, };
