// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The loaded filament a print draws from (resolved from `ams.tray_now`).
 */
export type Filament = { 
/**
 * `ams0`..`amsN` for an AMS tray, or `external` for the external spool.
 */
location: string, 
/**
 * Material, e.g. `PLA` (`tray_type`).
 */
material: string | null, 
/**
 * Display name, e.g. `PLA Matte` (`tray_sub_brands`).
 */
name: string | null, 
/**
 * Colour as reported (`tray_color`), e.g. `000000FF` (RGBA hex).
 */
color: string | null, };
