// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A decoded HMS alert (the wire view of [`crate::core::hms::HmsEntry`]).
 * `severity` is the **raw** bits — label conventions conflict across sources,
 * so we expose the number and link to the wiki rather than bundling a table.
 */
export type HmsAlert = { 
/**
 * Canonical underscore form, e.g. `HMS_0300_0100_0001_0007`.
 */
code: string, 
/**
 * Hyphen form Bambu shows on-screen, e.g. `0300-0100-0001-0007`.
 */
code_hyphen: string, 
/**
 * Raw severity bits (`code >> 16`); not mapped to a label.
 */
severity: number, 
/**
 * Originating subsystem: `motion_controller` / `mainboard` / `ams` /
 * `toolhead` / `xcam` / `unknown:0xNN`.
 */
module: string, 
/**
 * XCAM/micro-LiDAR code (only on X1-class hardware).
 */
is_lidar: boolean, 
/**
 * Deep link to Bambu's per-code troubleshooting page.
 */
wiki: string, 
/**
 * Raw `attr` int (escape hatch for re-deriving fields).
 */
attr: number, 
/**
 * Raw `code` int.
 */
raw_code: number, };
