// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Camera/timelapse settings from the `ipcam` report node (A1/P1: a JPEG-stream
 * camera). The `timelapse` field is the printer's *actual* timelapse setting,
 * which is how an `ipcam_timelapse` command is verified (the ACK alone only
 * says it was accepted — same caveat as the chamber light).
 */
export type Ipcam = { 
/**
 * `timelapse` mode (`enable`/`disable`) — whether a timelapse is recorded
 * during prints.
 */
timelapse: string | null, 
/**
 * `ipcam_record` mode (`enable`/`disable`).
 */
record: string | null, 
/**
 * Stream resolution, e.g. `1080p`.
 */
resolution: string | null, };
