// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `lights_report` entry: an LED node and its mode (`on`/`off`).
 */
export type LightReport = { node: string, mode: string, };
