// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Peripheral online state (`online`).
 */
export type Online = { 
/**
 * AHB bus present (`ahb`).
 */
ahb: boolean | null, 
/**
 * RFID reader present (`rfid`).
 */
rfid: boolean | null, 
/**
 * Reported version counter (`version`).
 */
version: number | null, };
