// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ams } from "./Ams";
import type { DeviceError } from "./DeviceError";
import type { Filament } from "./Filament";
import type { HmsAlert } from "./HmsAlert";
import type { Ipcam } from "./Ipcam";
import type { LightReport } from "./LightReport";
import type { Online } from "./Online";
import type { Upgrade } from "./Upgrade";
import type { Upload } from "./Upload";

/**
 * The fields of a printer `print` report that matter for monitoring.
 */
export type PrinterStatus = { 
/**
 * Coarse job state, e.g. `IDLE`, `RUNNING`, `PAUSE`, `FINISH`, `FAILED`.
 */
gcode_state: string | null, 
/**
 * `print_error` code (0 = none).
 */
print_error: number | null, 
/**
 * Typed view of a non-zero `print_error` (a device-level fault, distinct
 * from HMS — observed: a failing SD card surfaced `0x0500C010` here while
 * `hms` was empty). `None` when there is no active error.
 */
error: DeviceError | null, 
/**
 * Progress percentage (`mc_percent`).
 */
mc_percent: number | null, 
/**
 * Current layer / total layers.
 */
layer_num: number | null, total_layer_num: number | null, 
/**
 * Remaining time in minutes (`mc_remaining_time`).
 */
remaining_time_min: number | null, 
/**
 * Current stage id (`stg_cur`). Read together with `gcode_state`: stage 0
 * is the no-special-stage default and appears while idle too.
 */
stg_cur: number | null, 
/**
 * Decoded name of `stg_cur` (e.g. `auto_bed_leveling`), or `None` for an
 * unknown/future stage id. See [`crate::core::stage`].
 */
stage: string | null, 
/**
 * `home_flag` bitfield (per-axis homed state); it changes during a home/move,
 * so it's one of the few report signals that reflect ad-hoc motion.
 */
home_flag: number | null, 
/**
 * Nozzle / bed temperatures and their targets (°C).
 */
nozzle_temper: number | null, nozzle_target: number | null, bed_temper: number | null, bed_target: number | null, 
/**
 * **Raw** `chamber_temper` value as reported. On A1/P1 this is emitted but
 * is not a real sensor — call [`PrinterStatus::real_chamber_temperature`]
 * for a value only when the model actually has a chamber sensor.
 */
chamber_temper_raw: number | null, 
/**
 * Part-cooling fan speed (`cooling_fan_speed`; arrives as a string).
 */
cooling_fan_speed: number | null, 
/**
 * Active print-speed level (`spd_lvl`): 1 silent, 2 standard, 3 sport,
 * 4 ludicrous. How a `print_speed` command is verified.
 */
spd_lvl: number | null, 
/**
 * Name of the running subtask/job (empty when idle).
 */
subtask_name: string | null, 
/**
 * The currently-loaded filament (the one the print uses), resolved from
 * `ams.tray_now` → the matching AMS tray or the external spool. `None` when
 * nothing is loaded or the report doesn't carry AMS data.
 */
filament: Filament | null, 
/**
 * All `lights_report` entries (each `{node, mode}`), e.g.
 * `chamber_light=off`. This is the printer's *actual* light state — distinct
 * from a `ledctrl` ACK, which only confirms acceptance (observed: a faulty
 * unit ACKs `ledctrl` but `lights_report` stays `off`). Look a node up with
 * [`PrinterStatus::light_mode`].
 */
lights: Array<LightReport>, 
/**
 * Camera/timelapse settings from the `ipcam` report node. `None` when the
 * report carries no `ipcam` object.
 */
ipcam: Ipcam | null, 
/**
 * Aux/part fan #1 (`big_fan1_speed`).
 */
big_fan1_speed: number | null, 
/**
 * Chamber/second big fan (`big_fan2_speed`; 0 on the fanless-chamber A1).
 */
big_fan2_speed: number | null, 
/**
 * Hotend/heatbreak fan (`heatbreak_fan_speed`). Dead → heat creep / jams.
 */
heatbreak_fan_speed: number | null, 
/**
 * Packed per-fan gear bitfield (`fan_gear`).
 */
fan_gear: number | null, 
/**
 * Feed-rate override percent (`spd_mag`, 100 = nominal); distinct from the
 * named `spd_lvl` tier and what actually moves the ETA.
 */
spd_mag: number | null, 
/**
 * Filename currently loaded/printing (`gcode_file`); `None` when idle.
 */
gcode_file: string | null, 
/**
 * Pre-print file preparation/download progress (`gcode_file_prepare_percent`).
 * Lets a viewer tell "preparing" from a stalled `mc_percent == 0`.
 */
gcode_file_prepare_percent: number | null, 
/**
 * Coarse motion-controller phase (`mc_print_stage`), cross-checks `stg_cur`.
 */
mc_print_stage: number | null, 
/**
 * Finer sub-phase within `mc_print_stage` (`mc_print_sub_stage`).
 */
mc_print_sub_stage: number | null, 
/**
 * Current gcode line number (`mc_print_line_number`); increments within a
 * layer, so it is a fine-grained liveness/stall signal.
 */
mc_print_line_number: number | null, 
/**
 * Job source/type (`print_type`), e.g. `idle` / `local` / `cloud`.
 */
print_type: string | null, 
/**
 * Queue of upcoming stage ids (`stg`); `stg_cur` is the current one.
 */
stg: Array<number>, 
/**
 * Installed nozzle diameter in mm (`nozzle_diameter`, e.g. `0.4`).
 */
nozzle_diameter: string | null, 
/**
 * Nozzle material (`nozzle_type`, e.g. `stainless_steel` / `hardened`).
 */
nozzle_type: string | null, 
/**
 * Whether an SD card is present/mounted (`sdcard`).
 */
sdcard: boolean | null, 
/**
 * Top-level AMS state machine (`ams_status`): idle/loading/unloading code.
 */
ams_status: number | null, 
/**
 * Top-level AMS RFID read state (`ams_rfid_status`).
 */
ams_rfid_status: number | null, 
/**
 * Hardware switch / filament-presence / door sensor bits (`hw_switch_state`).
 */
hw_switch_state: number | null, 
/**
 * Wi-Fi signal strength (`wifi_signal`, e.g. `-50dBm`). The capture's
 * `<redacted>` sentinel is filtered to `None`.
 */
wifi_signal: string | null, 
/**
 * Cloud/print task id (`task_id`).
 */
task_id: string | null, 
/**
 * Subtask id (`subtask_id`), pairs with `subtask_name`.
 */
subtask_id: string | null, 
/**
 * Project id (`project_id`).
 */
project_id: string | null, 
/**
 * Slicing/print profile id (`profile_id`).
 */
profile_id: string | null, 
/**
 * The printer's own report counter (`sequence_id`); detects dropped/reordered
 * reports.
 */
sequence_id: string | null, 
/**
 * Device lifecycle/build channel (`lifecycle`, e.g. `product`).
 */
lifecycle: string | null, 
/**
 * Full AMS inventory (all units & trays), built from `ams` + `vt_tray`.
 * `filament` above remains a convenience pointer to the loaded tray.
 */
ams: Ams | null, 
/**
 * Firmware-update availability/progress (`upgrade_state`).
 */
upgrade: Upgrade | null, 
/**
 * Peripheral online state (`online`: AHB / RFID bus presence).
 */
online: Online | null, 
/**
 * In-progress file upload/transfer (`upload`).
 */
upload: Upload | null, 
/**
 * Decoded HMS alerts (the device's primary fault/warning channel). Empty
 * when healthy; separate from `error`/`print_error`. See [`crate::core::hms`].
 */
hms: Array<HmsAlert>, };
