// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Firmware-update availability/progress (`upgrade_state`).
 */
export type Upgrade = { 
/**
 * Whether an update is available/pending (`new_version_state`).
 */
new_version_state: number | null, 
/**
 * Non-zero ⇒ a flash is in progress (`cur_state_code`).
 */
cur_state_code: number | null, 
/**
 * Activity status (`status`, e.g. `IDLE`).
 */
status: string | null, 
/**
 * Failed-update error code (`err_code`).
 */
err_code: number | null, };
