// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * In-progress file upload/transfer (`upload`).
 */
export type Upload = { 
/**
 * Transfer status (`status`, e.g. `idle`).
 */
status: string | null, 
/**
 * Transfer progress percent (`progress`).
 */
progress: number | null, 
/**
 * Status message (`message`).
 */
message: string | null, };
